<a href="https://colab.research.google.com/github/2100032530/python-basics-assignment/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
marks=np.array([82,99,87,54,98,43])
marks_list=[82,99,87,54,98,43]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

[82 99 87 54 98 43]
<class 'numpy.ndarray'>
[82, 99, 87, 54, 98, 43]
<class 'list'>


In [ ]:
marks=np.array(["sowmya","pratik","priya"])
marks_list=["sowmya","pratik","priya"]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

['sowmya' 'pratik' 'priya']
<class 'numpy.ndarray'>
['sowmya', 'pratik', 'priya']
<class 'list'>


numpy supports element wise operation


In [ ]:
print(marks+5)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('int64')) -> None

In [ ]:
print(marks/5) # normal division

TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
print(marks//5) #floor division - gives only floor value no decimal value

TypeError: ufunc 'floor_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
prices=[20,50,40]
quantity=[2,5,6]
print(prices*quantity)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
prices=np.array([20,50,40])
quantity=np.array([2,5,6])
print(prices*quantity)

[ 40 250 240]


In [ ]:
arr1=np.array([1,2])
arr2=np.array([3])
print(arr1*arr2)
print(arr1.shape)
print(arr2.shape)

[3 6]
(2,)
(1,)


In [ ]:
arr=np.array([1,2,3.0])
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [ ]:
arr=np.array([1,1.9,"string"])
print(arr)
for i in arr:
  print(type(i))
  break

['1' '1.9' 'string']
<class 'numpy.str_'>


In [ ]:
arr=np.array([1,True])

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
ones=np.ones(12)
print(ones)
for i in ones:
  print(type(i))
  break

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [ ]:
print(np.full(5,9))  # full(parameter1,parameter2) - parameter1 -how many times you want to print that value , parameter2- what value u want to print

[9 9 9 9 9]


In [ ]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [ ]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.linspace(1,10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
marks=np.array([82,99,87,54,98,43])
print(marks.shape)
print(marks.size)
print(marks.ndim)
print(marks.dtype)
print(len(marks))

(6,)
6
1
int64
6


In [ ]:
a_list=[82,99,87,54,98,43]
b_list=[82,99,87,54,98,43]

marks1=np.array([82,99,87,54,98,43])
marks2=np.array([82,99,87,54,98,43])
print(a_list+b_list) # here + means concatenation of two lists not element wise addition
print(marks1+marks2) # here element wise operation is perfrmed

[82, 99, 87, 54, 98, 43, 82, 99, 87, 54, 98, 43]
[164 198 174 108 196  86]


In [ ]:
marks1=np.array([82,99,87,54,98,43,67,45,23,12])
print(marks1.sum())
print(marks1.mean())
print(marks1.min())
print(marks1.max())

610
61.0
12
99


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.ndim)

(6,)
1


In [ ]:
arr=np.array([[1,2],[3,4]])
print(arr.shape)
print(arr.ndim)

(2, 2)
2


In [ ]:
arr=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(arr.shape)
print(arr.ndim)


(2, 2, 2)
3


shapes and dimensions

In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)
print(a.T)
print(a.shape)
print(a.ndim)

[10 20 30 40 50]
[10 20 30 40 50]
(5,)
1


In [ ]:
a=np.array([[10],[20],[30],[40],[50]])
print(a)
print(a.T)
print(a.T.shape)
print(a.shape)
print(a.ndim)

[[10]
 [20]
 [30]
 [40]
 [50]]
[[10 20 30 40 50]]
(1, 5)
(5, 1)
2


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.T)
print(b.shape)
print(b.T.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


In [ ]:
c=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(c.shape)



(2, 2, 2)


Reshape

In [ ]:
import numpy as np
numbers=np.arange(1,13)
print(numbers.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
print(numbers.reshape(-1,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
c=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(c.reshape(-1)) #convert high dimension to 1d directly
print(c.flatten()) #convert high dimension to 1d directly

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4]


Checking numpy library speed

In [ ]:
import time
import numpy as np
size=10000000
numbers=list(range(size))
list_start_time=time.time()
for i,v in enumerate(numbers):
  numbers[i]=v+1
list_end_time=time.time()

numpy_array=np.arange(size)
array_start_time=time.time()
result_array=numpy_array+1
numpy_end_time=time.time()
list_time=list_end_time - list_start_time
array_time=numpy_end_time-array_start_time

print(f"{list_time:.4f} is time taken by list")
print(f"{array_time:.4f} is time taken by array")



1.5281 is time taken by list
0.0342 is time taken by array


In [ ]:
marks=np.array([[85,92,78],[90,88,95],[72,65,80],[95,91,89]])
print(marks[0])

[85 92 78]


In [ ]:
print(marks[2])

[72 65 80]


suppose if we want only first column and all the rows

In [ ]:
print(marks[:,0])

[85 90 72 95]


In [ ]:
print(marks[:,2])

[78 95 80 89]


In [ ]:
print(marks[0:2,:])

[[85 92 78]
 [90 88 95]]


broadcasting - numpy way of doing math operatons - [+,-,/,//] on arrays of different shapes

random

In [ ]:
print(np.random.randint(0,8,size=5,dtype=int))

[1 3 4 2 3]


In [ ]:
print(np.random.random(7))

[0.42445071 0.83980942 0.45646306 0.05375357 0.08143696 0.37866722
 0.77945321]


In [ ]:
print(np.random.uniform(10,30,size=5))

[19.53676879 21.93074982 17.55931802 14.77124071 15.54449478]


In [ ]:
print(np.random.choice(np.random.uniform(10,30,size=5),size=4))

[15.90808472 24.37848456 23.74336068 23.74336068]


In [ ]:
arr1=np.random.uniform(10,40,size=8)
print(arr1)
np.random.shuffle(arr1)
print(arr1)

[22.02617115 27.11119584 30.27173972 17.12073815 35.74020015 28.24220646
 13.37960312 30.07018696]
[13.37960312 35.74020015 28.24220646 22.02617115 27.11119584 30.07018696
 30.27173972 17.12073815]


In [ ]:
cities=np.array(['mumbai','chennai'])
print(np.random.choice(cities))

mumbai


In [ ]:
np.random.seed(12)
print(np.random.randint(1,100,size=5))

[76 28  7  3  4]


In [ ]:
np.random.seed(12)
print(np.random.randint(1,100,size=5))

[76 28  7  3  4]


In [ ]:
num_students=10

np.random.seed(20)

names=np.random.choice(["Ravi","Nirmala","Pratik","sowmya"],size=num_students)
print(names)

cities=np.random.choice(['hyderabad','mumbai','warangal','kolhapur'],size=num_students)
print(cities)

ages=np.random.randint(18,25,size=num_students)
print(ages)

maths_marks=np.random.randint(70,95,size=10)
print(maths_marks)

physics_marks=np.random.randint(60,90,size=10)
print(physics_marks)

chemistry_marks=np.random.randint(70,100,size=10)
print(chemistry_marks)



['sowmya' 'Pratik' 'sowmya' 'sowmya' 'Ravi' 'Pratik' 'Nirmala' 'Ravi'
 'sowmya' 'Pratik']
['kolhapur' 'warangal' 'hyderabad' 'warangal' 'hyderabad' 'mumbai'
 'warangal' 'warangal' 'kolhapur' 'kolhapur']
[18 23 24 24 24 18 19 23 23 20]
[76 83 81 73 80 81 83 89 84 70]
[70 71 66 71 78 63 89 73 77 84]
[81 86 88 85 96 97 77 81 92 99]


In [ ]:
cities=np.random.choice(['hyderabad','mumbai','warangal','kolhapur'],size=num_students)
print(cities)

['kolhapur' 'warangal' 'hyderabad' 'kolhapur' 'mumbai' 'warangal'
 'kolhapur' 'kolhapur' 'hyderabad' 'warangal']


In [ ]:
ages=np.random.randint(18,25,size=num_students)
print(ages)

[24 20 18 22 24 21 23 19 23 24]


In [ ]:
maths_marks=np.random.randint(70,95,size=7)
print(maths_marks)

[86 70 84 94 85 92 71]


In [ ]:
physics_marks=np.random.randint(60,90,size=7)
print(physics_marks)

[84 64 60 64 61 71 72]


In [ ]:
chemistry_marks=np.random.randint(70,100,size=7)
print(chemistry_marks)

[75 81 91 89 74 91 81]


In [ ]:
with open("students.txt","w") as file:
  file.write("name ,city , maths_marks , physics_marks ,chemistry_marks\n")
  for i in range(num_students):
      file.write(f"{names[i]},{cities[i]},{ages[i]},{maths_marks[i]},{physics_marks[i]},{chemistry_marks[i]}\n")